export const TRANSLATIONS = {
  en: {
    brand: "garibook",
    nav: [
      { name: "About Us", href: "#about" },
      { name: "Earn With Garibook", href: "#earn" },
      { name: "Garibook Business", href: "#business" },
      { name: "Garibook Club", href: "#club" },
      { name: "Campaign", href: "#campaign" },
      { name: "Blogs", href: "#blogs" },
    ],
    login: "login",
    hero: {
      titles: [
        "Luxury Trips with Comfort",
        "Your Journey Starts Here ...",
        "Assurance of Effortless Travel",
      ],
      description:
        "Choose your city, pick your car and enjoy the journey with Garibook's best drivers.",
      downloadBtn: "Download App",
      tabs: { carRental: "Car Rental", airportRental: "Airport Rental" },
      tripTypes: { oneWay: "One Way", roundWay: "Round Way", hourly: "Hourly" },
      form: {
        chooseCar: "Choose a Car",
        chooseCarPlaceholder: "Select Car Type",
        pickupLocation: "Pickup Location",
        pickupPlaceholder: "Enter Pickup Location",
        dropoffLocation: "Drop-off Location",
        dropoffPlaceholder: "Enter Drop-off Location",
        pickupDate: "Pickup Date & Time",
        returnDate: "Return Date & Time",
        selectHours: "Select Hours",
        minHoursNotice: "Minimum 2 hours is required for an hourly trip.",
        datePlaceholder: "MM/DD/YYYY 00:00 PM",
        continueBtn: "Continue",
      },
    },
    stats: {
      title: "From Everyday Rides to Meaningful Journeys",
      items: [
        { count: "300,000+", label: "Trip Requests" },
        { count: "850,000+", label: "Total Customers" },
        { count: "35,000+", label: "Active Drivers" },
        { count: "64", label: "District Covered" },
      ],
    },
    services: {
      heading: "Our Services",
      rides: "Rides",
      business: "Garibook Business",
      club: "Garibook Club",
      vms: "VMS",
      everyRideHeading: "Every Ride One Platform",
      intercity: "Intercity Car Rental",
      intercityDesc: "Travel between cities with comfort and confidence.",
      rideshare: "Ride share",
      rideshareDesc: "Go anywhere in the city, quickly and easily.",
      airport: "Airport Rental",
      airportDesc:
        "Whether you're flying abroad or returning home, enjoy a comfortable and worry-free airport journey.",
      hourly: "Hourly Rental",
      hourlyDesc: "Rent a car by the hour, tailored to your needs.",
    },
    business: {
      heading: "Modern Car Rentals for Business",
      desc: "Simplify your corporate transportation, ensure on-time team mobility, and gain control with our VMS.",
      learnMore: "Learn More",
    },
    club: {
      heading: "Turn Your Car into Earnings with Garibook Club",
      desc: "Garibook Club is more than just a community. Join a vibrant network of car enthusiasts, all fueled by the same passion: the open road and the thrill of making money doing what they love.",
    },
    vms: {
      heading: "Vehicle Management System - VMS",
      desc: "Just like Garibook Business makes traveling easy for your team, our Vehicle Management System (VMS) helps you take care of your own cars.",
    },
    freedom: {
      heading: "Freedom in Every Journey",
      chooseCar: "Choose the Car",
      chooseCarDesc: "Pick what suits your comfort.",
      chooseDriver: "Choose the Driver",
      chooseDriverDesc: "Based on ratings and reviews.",
      chooseFare: "Choose the Fare",
      chooseFareDesc: "Select the bid that fits your budget.",
    },
    gallery: {
      heading: "More Than Miles — We Bring People Together",
      quoteDesc:
        '"Quick and easy booking! I needed a ride to the airport at 5 AM, and the driver arrived on time. The car was clean, and the ride was smooth. Definitely my go-to taxi service from now on!"',
      airportRentals: "Airport Rentals",
      familyTrips: "Family Trips",
      longTours: "Long Tours",
    },
    newsroom: {
      heading: "We Featured by Top news Platforms",
      readArticle: "Read Article",
    },
    testimonials: {
      heading: "Our Passengers Speak For Us",
      desc: "Our journey was seamless and enjoyable from start to finish. The booking process was straightforward, and the staff were incredibly attentive, ensuring we felt comfortable throughout the trip.",
      banker: "Banker",
      serviceHolder: "Service Holder",
    },
    bookingArrival: {
      heading: "From Booking to Arrival It's All in Your Hands",
      downloadApp: "Download App",
    },
    smartDriver: {
      heading: "Be a Smart Driver",
      subheading: "0% Commission 100% Freedom",
      cta: "Download Smart Driver App",
    },
    blog: {
      heading: "Beyond Destinations",
      desc: "Discover travel hacks, guides, and inspirations for your next intercity trip with Garibook.",
      showAll: "Show All Blogs",
    },
    downloadApp: {
      heading: "Download Garibook Mobile App",
      subtext: "Download our Customer, Smart Driver and Enterprise App",
      cta: "Download App",
    },
    footer: {
      about: "About Us",
      reviews: "Customer Reviews",
      career: "Career",
      newsroom: "Newsroom",
      map: "Garibook Map",
      servicesHeading: "Services",
      intercity: "Intercity Rental",
      airport: "Airport Pick and Drop",
      hourly: "Hourly Rental",
      vms: "Vehicle Management System (VMS)",
      partnerHeading: "Become Our Partner",
      smartDriver: "Become a Smart Driver",
      club: "Become a member of Garibook Club",
      business: "Garibook Business for Corporate Travel",
      contactsHeading: "Contacts",
      downloadHeading: "Download Our Garibook Mobile App",
      downloadApp: "Download App",
      visitWebsite: "Visit Website",
      terms: "Terms & Conditions",
      privacy: "Privacy Policy",
    },
  },
  bn: {
    brand: "গারিবুক",
    nav: [
      { name: "আমাদের সম্পর্কে", href: "#about" },
      { name: "গারিবুক আয়", href: "#earn" },
      { name: "গারিবুক বিজনেস", href: "#business" },
      { name: "গারিবুক ক্লাব", href: "#club" },
      { name: "ক্যাম্পেইন", href: "#campaign" },
      { name: "ব্লগ", href: "#blogs" },
    ],
    login: "লগইন",
    hero: {
      titles: [
        "আরামের সাথে সুনিশ্চিত ভ্রমণ",
        "আপনার যাত্রা শুরু হোক এখান থেকেই...",
        "সহজ ও নিশ্চিন্ত ভ্রমণের আস্থা",
      ],
      description:
        "সেরা কোয়ালিটির গাড়িতে, ভেরিফাইড ড্রাইভারের সাথে গন্তব্যে পৌঁছে যান নিরাপদে।",
      downloadBtn: "অ্যাপ ডাউনলোড করুন",
      tabs: { carRental: "কার রেন্টাল", airportRental: "এয়ারপোর্ট রেন্টাল" },
      tripTypes: { oneWay: "ওয়ান ওয়ে", roundWay: "রাউন্ড ওয়ে", hourly: "আওয়ারলি" },
      form: {
        chooseCar: "একটি গাড়ি নির্বাচন করুন",
        chooseCarPlaceholder: "গাড়ি নির্বাচন করুন",
        pickupLocation: "পিকআপ লোকেশন",
        pickupPlaceholder: "পিকআপ লোকেশন লিখুন",
        dropoffLocation: "ড্রপ-অফ লোকেশন",
        dropoffPlaceholder: "ড্রপ-অফ লোকেশন লিখুন",
        pickupDate: "পিকআপ তারিখ ও সময়",
        returnDate: "রিটার্ন তারিখ ও সময়",
        selectHours: "ঘণ্টা নির্বাচন করুন",
        minHoursNotice: "আওয়ারলি ট্রিপের জন্য সর্বনিম্ন ২ ঘণ্টা প্রয়োজন।",
        datePlaceholder: "দিন/মাস/বছর ০০:০০ PM",
        continueBtn: "এগিয়ে যান",
      },
    },
    stats: {
      title: "দৈনন্দিন যাত্রা থেকে স্মরণীয় ভ্রমণ",
      items: [
        { count: "৩,০০,০০০+", label: "ট্রিপ রিকুয়েস্ট" },
        { count: "৮,৫০,০০০+", label: "মোট কাস্টমার" },
        { count: "৩৫,০০০+", label: "অ্যাক্টিভ ড্রাইভার" },
        { count: "৬৪", label: "জেলা কভার্ড" },
      ],
    },
    services: {
      heading: "আমাদের সেবাসমূহ",
      rides: "রাইড",
      business: "গারিবুক বিজনেস",
      club: "গারিবুক ক্লাব",
      vms: "ভিএমএস",
      everyRideHeading: "প্রতিটি রাইড, একটি প্ল্যাটফর্ম",
      intercity: "ইন্টারসিটি কার রেন্টাল",
      intercityDesc: "আরাম ও নিশ্চিন্তে শহর থেকে শহরে ভ্রমণ করুন।",
      rideshare: "রাইড শেয়ার",
      rideshareDesc: "শহরের যেকোনো জায়গায় দ্রুত ও সহজে যান।",
      airport: "এয়ারপোর্ট রেন্টাল",
      airportDesc: "বিদেশ যাত্রা হোক বা দেশে ফেরা, উপভোগ করুন আরামদায়ক এয়ারপোর্ট যাত্রা।",
      hourly: "ঘণ্টাভিত্তিক রেন্টাল",
      hourlyDesc: "আপনার প্রয়োজন অনুযায়ী ঘণ্টাভিত্তিক গাড়ি ভাড়া নিন।",
    },
    business: {
      heading: "ব্যবসার জন্য আধুনিক কার রেন্টাল",
      desc: "আপনার প্রতিষ্ঠানের পরিবহন সহজ করুন এবং আমাদের ভিএমএস দিয়ে নিয়ন্ত্রণ রাখুন।",
      learnMore: "আরও জানুন",
    },
    club: {
      heading: "গারিবুক ক্লাবের মাধ্যমে আপনার গাড়ি থেকে আয় করুন",
      desc: "গারিবুক ক্লাব শুধু একটি কমিউনিটি নয়। যোগ দিন গাড়িপ্রেমীদের এক প্রাণবন্ত নেটওয়ার্কে।",
    },
    vms: {
      heading: "ভেহিকল ম্যানেজমেন্ট সিস্টেম - ভিএমএস",
      desc: "গারিবুক বিজনেস যেমন আপনার টিমের যাত্রা সহজ করে, তেমনি ভিএমএস আপনার নিজের গাড়ির যত্ন নিতে সাহায্য করে।",
    },
    freedom: {
      heading: "প্রতিটি যাত্রায় স্বাধীনতা",
      chooseCar: "গাড়ি বেছে নিন",
      chooseCarDesc: "আপনার আরামের জন্য উপযুক্তটি বেছে নিন।",
      chooseDriver: "চালক বেছে নিন",
      chooseDriverDesc: "রেটিং ও রিভিউ অনুযায়ী।",
      chooseFare: "ভাড়া বেছে নিন",
      chooseFareDesc: "আপনার বাজেটে মানানসই অফার বেছে নিন।",
    },
    gallery: {
      heading: "শুধু মাইল নয় — আমরা মানুষকে কাছে আনি",
      quoteDesc:
        '"দ্রুত এবং সহজ বুকিং! ভোর ৫টায় আমার এয়ারপোর্টের জন্য গাড়ির প্রয়োজন ছিল এবং ড্রাইভার ঠিক সময়ে চলে এসেছিলেন। গাড়িটি পরিষ্কার ছিল এবং যাত্রাটিও খুব আরামদায়ক ছিল। নিঃসন্দেহে এটি এখন থেকে আমার সেরা পছন্দ!"',
      airportRentals: "এয়ারপোর্ট রেন্টাল",
      familyTrips: "পারিবারিক ভ্রমণ",
      longTours: "দীর্ঘ ভ্রমণ",
    },
    newsroom: {
      heading: "শীর্ষস্থানীয় নিউজ প্ল্যাটফর্মে আমরা",
      readArticle: "পড়ুন",
    },
    testimonials: {
      heading: "আমাদের যাত্রীদের অভিজ্ঞতা",
      desc: "আমাদের যাত্রা শুরু থেকে শেষ পর্যন্ত ছিল ঝামেলাহীন ও আনন্দদায়ক। বুকিং প্রক্রিয়া সহজ ছিল এবং স্টাফরা অত্যন্ত মনোযোগী ছিলেন, যা পুরো যাত্রায় আমাদের স্বাচ্ছন্দ্যবোধ নিশ্চিত করেছিল।",
      banker: "ব্যাংকার",
      serviceHolder: "চাকরিজীবী",
    },
    bookingArrival: {
      heading: "বুকিং থেকে পৌঁছানো — সবকিছু আপনার হাতের মুঠোয়",
      downloadApp: "অ্যাপ ডাউনলোড করুন",
    },
    smartDriver: {
      heading: "স্মার্ট ড্রাইভার হোন",
      subheading: "০% কমিশন ১০০% স্বাধীনতা",
      cta: "স্মার্ট ড্রাইভার অ্যাপ ডাউনলোড করুন",
    },
    blog: {
      heading: "গন্তব্যের বাইরেও",
      desc: "গারিবুকের সাথে আপনার পরবর্তী ইন্টারসিটি ভ্রমণের জন্য টিপস ও গাইড জানুন।",
      showAll: "সব ব্লগ দেখুন",
    },
    downloadApp: {
      heading: "গারিবুক মোবাইল অ্যাপ ডাউনলোড করুন",
      subtext: "আমাদের কাস্টমার, স্মার্ট ড্রাইভার ও এন্টারপ্রাইজ অ্যাপ ডাউনলোড করুন",
      cta: "অ্যাপ ডাউনলোড করুন",
    },
    footer: {
      about: "আমাদের সম্পর্কে",
      reviews: "গ্রাহক রিভিউ",
      career: "ক্যারিয়ার",
      newsroom: "নিউজরুম",
      map: "গারিবুক ম্যাপ",
      servicesHeading: "সেবাসমূহ",
      intercity: "ইন্টারসিটি রেন্টাল",
      airport: "এয়ারপোর্ট পিক এন্ড ড্রপ",
      hourly: "ঘণ্টাভিত্তিক রেন্টাল",
      vms: "ভেহিকল ম্যানেজমেন্ট সিস্টেম (ভিএমএস)",
      partnerHeading: "আমাদের পার্টনার হোন",
      smartDriver: "স্মার্ট ড্রাইভার হোন",
      club: "গারিবুক ক্লাবের সদস্য হোন",
      business: "কর্পোরেট ভ্রমণের জন্য গারিবুক বিজনেস",
      contactsHeading: "যোগাযোগ",
      downloadHeading: "গারিবুক মোবাইল অ্যাপ ডাউনলোড করুন",
      downloadApp: "অ্যাপ ডাউনলোড করুন",
      visitWebsite: "ওয়েবসাইট দেখুন",
      terms: "শর্তাবলী",
      privacy: "গোপনীয়তা নীতি",
    },
  },
};